version: '3.9'
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  order-service:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: OrderService
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis

  payment-service:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    container_name: PaymentService
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS__HOST=redis
    depends_on:
      - redis